[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"

[project]
name = 'crlib'
version = '0.1.0'

[tool.setuptools]
packages = ['crlib', 'crlib2']

[project.scripts]
fit1d = "crlib2:fit1d"
write_features = "crlib2:write_features"
